package com.silentvoix.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Calm deep-teal palette; text/background pairs keep at least WCAG AA contrast.

internal val LightColors = lightColorScheme(
    primary = Color(0xFF005F66),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB3ECF1),
    onPrimaryContainer = Color(0xFF001F22),
    secondary = Color(0xFF475F62),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCBE7EA),
    onSecondaryContainer = Color(0xFF021F22),
    tertiary = Color(0xFF4B5C92),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDBE1FF),
    onTertiaryContainer = Color(0xFF01174B),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF7FAFA),
    onBackground = Color(0xFF111718),
    surface = Color(0xFFF7FAFA),
    onSurface = Color(0xFF111718),
    surfaceVariant = Color(0xFFDBE4E5),
    onSurfaceVariant = Color(0xFF3A4749),
    outline = Color(0xFF5E6D6F),
    outlineVariant = Color(0xFFBFC8C9),
    inverseSurface = Color(0xFF263233),
    inverseOnSurface = Color(0xFFECF2F2),
    inversePrimary = Color(0xFF82D3DA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF1F5F5),
    surfaceContainer = Color(0xFFEBEFEF),
    surfaceContainerHigh = Color(0xFFE5E9E9),
    surfaceContainerHighest = Color(0xFFDFE3E4),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFF82D3DA),
    onPrimary = Color(0xFF00363B),
    primaryContainer = Color(0xFF004F55),
    onPrimaryContainer = Color(0xFFB3ECF1),
    secondary = Color(0xFFAFCBCE),
    onSecondary = Color(0xFF193436),
    secondaryContainer = Color(0xFF304A4D),
    onSecondaryContainer = Color(0xFFCBE7EA),
    tertiary = Color(0xFFB4C5FF),
    onTertiary = Color(0xFF1B2D61),
    tertiaryContainer = Color(0xFF334478),
    onTertiaryContainer = Color(0xFFDBE1FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E1415),
    onBackground = Color(0xFFDEE4E4),
    surface = Color(0xFF0E1415),
    onSurface = Color(0xFFDEE4E4),
    surfaceVariant = Color(0xFF3F4849),
    onSurfaceVariant = Color(0xFFC3CDCE),
    outline = Color(0xFF8D9899),
    outlineVariant = Color(0xFF3F4849),
    inverseSurface = Color(0xFFDEE4E4),
    inverseOnSurface = Color(0xFF2B3132),
    inversePrimary = Color(0xFF005F66),
    surfaceContainerLowest = Color(0xFF090F10),
    surfaceContainerLow = Color(0xFF161D1D),
    surfaceContainer = Color(0xFF1A2122),
    surfaceContainerHigh = Color(0xFF252B2C),
    surfaceContainerHighest = Color(0xFF2F3637),
)
